

name: Deploy Azure Function App
on:
  push:
    branches:
      - main   

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python and install dependencies
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run checks
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 ../../src/portfolio-assistant
          flake8 ../../ChatFunction

      - name: Run tests
        run: pytest

      # Deploy to Azure Functions
      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          package: '../../src/portfolio-assistant'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
