

name: Deploy Azure Function App
on:
  push:
    branches:
      - main   
  workflow_dispatch:
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.10'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv /tmp/venv
          source /tmp/venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          source /tmp/venv/bin/activate
          flake8 ./src/portfolio_assistant
          flake8 ./chat_function

      - name: Run tests
        run: |
          source /tmp/venv/bin/activate
          pytest

      - name: Clean up before deployment
        run: |
          rm -rf /tmp/venv
          find . -type d -name "__pycache__" -exec rm -rf {} +
          rm -rf .pytest_cache

      - name: Prepare deploy package
        run: |
          rm -rf package
          mkdir -p package
          cp host.json requirements.txt package/
          cp -r chat_function package/chat_function
          cp -r src package/src

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          package: 'package'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}